### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud) for [Kodi add-ons: skins/skin.copacetic](https://kodi.weblate.cloud/projects/kodi-add-ons-skins/skin-copacetic/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by gade01 — APPROVED** [review]
Everything at Weblate weems to be fixed and looking good now.

**Comment by realcopacetic** [comment]
Thanks @gade01 - really appreciate your help on this. I must have messed it up when I added a new brand for and I had no idea what I was doing, apologies for wasting your time on this, but really appreciate your help

**Comment by gade01** [comment]
@realcopacetic No worries at all.
It took 30 minutes to fix  :)

Do you still prefer Weblate to use master branch?

**Comment by realcopacetic** [comment]
Maybe you could advise actually @gade01 as I don't think I have a very good workflow. Right now I'm using master as my main dev branch for Omega, then cherry picking every commit that can be ported over to my Nexus branch and manually resolving any conflicts. This feels very manual, but I'm really not well versed in general coding practices or Github methodologies. 

What is the recommended way for syncing weblate across multiple branches?

**Comment by realcopacetic** [comment]
> @realcopacetic No worries at all. It took 30 minutes to fix :)
> 
> Do you still prefer Weblate to use master branch?

So sorry about wasting your time on this! I bought you a coffee by way of saying thanks :D

**Pull request merged**
